import os
from pathlib import Path
from dotenv import load_dotenv
from openai import OpenAI

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=BASE_DIR / ".env")

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)
def generate_refined_caption(model_caption, pose_points):

    prompt = f"""
You are an expert human pose captioning system.

You are given:
1. A raw caption generated by a trained pose-captioning model.
2. 66 normalized body landmark values.

Important:
The raw model caption may contain mistakes. Do NOT blindly trust it.
Use the pose landmark values as the main source of truth.
Use the raw model caption only as a weak hint.
If the raw caption conflicts with the pose points, ignore the wrong parts and generate your own corrected caption.

Task:
Generate ONE detailed, natural, human-readable full-body pose caption.

Rules:
- Do not mention AI.
- Do not mention MediaPipe.
- Do not mention landmarks.
- Do not mention coordinates.
- Do not mention angles.
- Do not say "the model says".
- Generate a detailed natural full-body pose description.
- Describe arms, legs, posture, orientation, and overall body stance naturally.
- Make the caption human-like and visually descriptive.
- Use complete flowing sentences.
- Keep it realistic and natural.
- Output ONLY the final caption.

Raw model caption:
{model_caption}

Pose landmark values:
{pose_points}
"""

    response = client.responses.create(
        model="gpt-5.5",
        input=prompt
    )

    return response.output_text.strip()